# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.TextField()),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('genre', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2017, 1, 16, 16, 23, 4, 609969))),
            ],
        ),
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('game_id', models.TextField()),
                ('score', models.IntegerField(null=True)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2017, 1, 16, 16, 23, 4, 609969))),
            ],
        ),
    ]
