# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0004_auto_20170116_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='highscore',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
